env:
  browser: true
  es6: true
  node: true

ignorePatterns:
  - dist
  - out
  - template
  - "packages/**/wasm/*.js"
  - "!.storybook"
  - storybook-static

plugins:
  - file-progress
  - tss-unused-classes

extends:
  - plugin:@foxglove/base
  - plugin:@foxglove/react
  - plugin:@foxglove/jest

settings:
  import/internal-regex: "^@foxglove"

rules:
  "@foxglove/license-header": error

  tss-unused-classes/unused-classes: error

  # show progress while linting
  file-progress/activate: warn

  # enabled in .eslintrc.ci.yaml
  prettier/prettier: off
  import/no-self-import: off
  import/no-duplicates: off

  id-denylist:
    - error
    - useEffectOnce
    - window # don't allow redefining window
  no-console: off # configured in no-restricted-syntax

  react/jsx-uses-react: off
  react/prop-types: off # Unnecessary with typescript validation
  react-hooks/exhaustive-deps:
    - error
    - additionalHooks: "(useAsync(?!AppConfigurationValue))|useCallbackWithToast"
  react/jsx-curly-brace-presence: [error, never]

  # The _sx_ property is slow
  # https://stackoverflow.com/questions/68383046/is-there-a-performance-difference-between-the-sx-prop-and-the-makestyles-function
  react/forbid-component-props:
    - error
    - forbid:
        - propName: "sx"
          message: "Use of the sx prop is not advised due to performance issues. Consider using alternative styling methods instead."

  no-warning-comments:
    - error
    - terms: ["fixme", "xxx", "todo"]
      location: anywhere

  no-restricted-imports:
    - error
    - paths:
        - name: "styled-components"
          message: "styled-components has been deprecated. Use tss-react/mui instead."

        - name: "@fluentui/react"
          message: "@fluentui/react has been deprecated. Use tss-react/mui instead."

        - name: "@mui/material"
          importNames: [styled]
          message: "@mui/styled has performance implications. Use tss-react/mui instead."
        - name: "@mui/material/styles/styled"
          message: "@mui/styled has performance implications. Use tss-react/mui instead."
        - name: "@mui/system"
          message: "@mui/styled has performance implications. Use tss-react/mui instead."
        - name: "@mui/system/styled"
          message: "@mui/styled has performance implications. Use tss-react/mui instead."
        - name: "@emotion/styled"
          message: "@emotion/styled has performance implications. Use tss-react/mui instead."

        - name: "lodash"
          importNames: [get]
          message: "Use optional chaining instead of lodash.get."
        - name: "lodash/get"
          message: "Use optional chaining instead of lodash.get."

  no-restricted-syntax:
    - error
    - selector: "MethodDefinition[kind='get'], Property[kind='get']"
      message: "Property getters are not allowed; prefer function syntax instead."
    - selector: "MethodDefinition[kind='set'], Property[kind='set']"
      message: "Property setters are not allowed; prefer function syntax instead."

    # We disable console methods here rather than using no-console so that it doesn't prohibit overrides such as "console.info = ..."
    - selector: "CallExpression[callee.object.name='console'][callee.property.name!=/^(warn|error|debug|assert)$/]"
      message: "Unexpected property on console object was called"

    - selector: "TSNullKeyword, Literal[raw=null]"
      message: >
        Prefer undefined instead of null. When required for React refs/components, use
        the `ReactNull` alias. Otherwise, if strictly necessary, disable this error with
        `// eslint-disable-next-line no-restricted-syntax`. For rationale, see:
        https://github.com/sindresorhus/meta/discussions/7"

  jest/no-done-callback: off # Can be a useful alternative to promises
  jest/expect-expect:
    [error, { assertFunctionNames: [expect*, sendNotification.expectCalledDuringTest] }]

overrides:
  - files: ["*.ts", "*.tsx"]
    extends:
      - plugin:@foxglove/typescript
    parserOptions:
      project: ./tsconfig.eslint.json
    rules:
      "@typescript-eslint/ban-ts-comment":
        - error
        - ts-expect-error: allow-with-description

      "@typescript-eslint/explicit-member-accessibility": error

      "@typescript-eslint/no-inferrable-types": off # It's sometimes useful to explicitly name to guard against future changes
      "@typescript-eslint/no-empty-function": off
      "@typescript-eslint/no-implied-eval": off # We need to use `new Function()`

      # These are related to `any` types, which we generally don't have except from imports
      "@typescript-eslint/no-unsafe-member-access": off
      "@typescript-eslint/no-unsafe-return": off
      "@typescript-eslint/no-unsafe-assignment": off
      "@typescript-eslint/no-unsafe-call": off

      "@typescript-eslint/require-await": off # Async functions without await are used to satisfy interface requirements

      # These could theoretically be turned on (or merit investigation) but are currently noisy
      "@typescript-eslint/no-misused-promises": off # Often used with e.g. useCallback(async () => {})
      "@typescript-eslint/restrict-template-expressions": off

      "@typescript-eslint/prefer-regexp-exec": off
      "@typescript-eslint/no-unnecessary-condition": error
      "@typescript-eslint/unbound-method": [error, { ignoreStatic: true }]

  - rules:
      "@typescript-eslint/no-explicit-any": off
    files:
      - "**/*.stories.tsx"
      - "**/*.test.tsx"
      - "**/*.test.ts"

  - rules:
      tss-unused-classes/unused-classes: off
    files:
      # Using @fluentui/makeStyles expecting deletion soon
      - packages/studio-base/src/components/Menu/Item.tsx
      - packages/studio-base/src/components/Menu/Menu.tsx

  - rules:
      no-restricted-imports: off
    files:
      # Ignore existing implementations of fluentui, styled-components, and @mui/styled
      - "packages/studio-base/src/components/Autocomplete.tsx"
      - "packages/studio-base/src/components/ChildToggle/index.tsx"
      - "packages/studio-base/src/components/ColorPicker/index.tsx"
      - "packages/studio-base/src/components/CopyText.tsx"
      - "packages/studio-base/src/components/DocumentDropListener.tsx"
      - "packages/studio-base/src/components/DropOverlay.tsx"
      - "packages/studio-base/src/components/EmptyPanelLayout.tsx"
      - "packages/studio-base/src/components/ErrorDisplay.tsx"
      - "packages/studio-base/src/components/Menu/Item.tsx"
      - "packages/studio-base/src/components/Menu/Menu.tsx"
      - "packages/studio-base/src/components/NotificationModal.tsx"
      - "packages/studio-base/src/components/Panel.tsx"
      - "packages/studio-base/src/components/PanelLayout.tsx"
      - "packages/studio-base/src/components/PanelList/index.tsx"
      - "packages/studio-base/src/components/PanelRoot.tsx"
      - "packages/studio-base/src/components/PanelToolbar/PanelActionsDropdown.tsx"
      - "packages/studio-base/src/components/PanelToolbar/ToolbarIconButton.tsx"
      - "packages/studio-base/src/components/PanelToolbar/index.tsx"
      - "packages/studio-base/src/components/PlaybackControls/PlaybackTimeDisplayMethod.tsx"
      - "packages/studio-base/src/components/PlaybackControls/Slider.stories.tsx"
      - "packages/studio-base/src/components/SegmentedControl.tsx"
      - "packages/studio-base/src/components/Sidebar/SidebarButton.tsx"
      - "packages/studio-base/src/components/Sidebar/index.tsx"
      - "packages/studio-base/src/components/SidebarContent.tsx"
      - "packages/studio-base/src/components/StudioToastProvider.tsx"
      - "packages/studio-base/src/components/TextHighlight.tsx"
      - "packages/studio-base/src/components/TimeBasedChart/index.tsx"
      - "packages/studio-base/src/components/Tooltip.tsx"
      - "packages/studio-base/src/panels/DataSourceInfo/index.tsx"
      - "packages/studio-base/src/panels/InternalLogs/index.tsx"
      - "packages/studio-base/src/panels/Log/FilterBar.tsx"
      - "packages/studio-base/src/panels/Log/index.tsx"
      - "packages/studio-base/src/panels/Parameters/AnimatedRow.tsx"
      - "packages/studio-base/src/panels/Plot/PathSettingsModal.tsx"
      - "packages/studio-base/src/panels/RawMessages/DiffSpan.tsx"
      - "packages/studio-base/src/panels/RawMessages/Metadata.tsx"
      - "packages/studio-base/src/panels/Tab/TabbedToolbar.tsx"
      - "packages/studio-base/src/panels/Tab/ToolbarTab.tsx"
      - "packages/studio-base/src/panels/Tab/index.tsx"
      - "packages/studio-base/src/panels/ThreeDimensionalViz/**/**/*"
      - "packages/studio-base/src/panels/URDFViewer/JointValueSliders.tsx"
      - "packages/studio-base/src/panels/URDFViewer/OverlayControls.tsx"
      - "packages/studio-base/src/panels/URDFViewer/index.tsx"
      - "packages/studio-base/src/panels/URDFViewer/useRobotDescriptionAsset.tsx"
      - "packages/studio-base/src/panels/diagnostics/DiagnosticStatus.tsx"
      - "packages/studio-base/src/panels/diagnostics/DiagnosticSummary.tsx"
      - "packages/studio-base/src/screens/LaunchPreferenceScreen.tsx"
      - "packages/studio-base/src/stories/PanelSetup.tsx"
      - "packages/studio-base/src/stories/storyHelpers.tsx"
      - "packages/studio-base/src/theme/ThemeProvider.tsx"
      - "packages/studio-base/src/theme/createFluentTheme.ts"
      - "packages/studio-base/src/theme/fluentComponents.ts"
      - "packages/studio-base/src/theme/index.stories.tsx"
      - "packages/studio-base/src/typings/fluentui.d.ts"
      - "packages/studio-base/src/typings/styled-components.d.ts"
